version: '3.7'

services:
  bgs:
    container_name: j2ee
    image: tomcat:jdk15
    depends_on:
      - "database"
    volumes:
      - "./resources:/opt/bgs/resources"
      #- "./target/ROOT.war:/opt/jboss/wildfly/standalone/deployments/bgStudio.war"
      - "./tomcat/webapps/bgStudio.war:/usr/local/tomcat/webapps/bgStudio.war"
    networks:
      - bgs_net
    ports:
      - "8080:8080"
    environment:
      BG_LOCAL_FOLDER: /opt/bgs
      BG_JDBC_DRIVER: com.mysql.jdbc.Driver
      BG_JDBC_URL: jdbc:mysql://database:3306/bg?autoReconnect=true&autoReconnectForPools=true
      BG_JDBC_USER: root
      BG_JDBC_PASSWORD: root

  database:
    container_name: database
    image: mariadb
    networks:
      - bgs_net
    volumes:
      - "./resources/database:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bg

volumes:
  bgs_volume:

networks:
  bgs_net: