db:
  image: mariadb:10.5.8
  environment:
    MYSQL_ROOT_PASSWORD: testazzo
    MYSQL_DATABASE: provaDB
    MYSQL_USER: bgstest
    MYSQL_PASSWORD: bgstest
#  ports:
#    - "3306:3306"
  volumes:
   - ./db:/docker-entrypoint-initdb.d

web:
  image: tomcat:jdk15
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: jdbc:mariadb://db:3306/provaDB?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: bgstest
    JDBC_PASS: bgstest
  ports:
   - "80:8080"
  volumes:
    - /home/paola/workspace/lavoro/artemat/###experiment/tomcatMariaDB/basicmavenwebapp/target/basicmavenwebapp.war:/usr/local/tomcat/webapps/hw.war
  links:
    - db
